name: Debug Build Failure

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  debug-build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Create local.properties
        run: |
          cat << EOF > local.properties
          sdk.dir=$ANDROID_HOME
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          MAPS_SAFE_CODE=${{ secrets.MAPS_SAFE_CODE }}
          EOF
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      # 停止所有 Gradle daemon
      - name: Stop Gradle daemons
        run: ./gradlew --stop || true
      
      # 清理项目
      - name: Clean project
        run: ./gradlew clean --no-daemon
      
      # 1. 首先尝试获取依赖树，检查依赖问题
      - name: Check dependencies
        run: ./gradlew app:dependencies --no-daemon --configuration debugCompileClasspath || true
      
      # 2. 尝试编译代码（不打包资源）
      - name: Compile Java code
        run: ./gradlew compileDebugJavaWithJavac --no-daemon --stacktrace --info || true
      
      # 3. 检查资源
      - name: Check resources
        run: ./gradlew processDebugResources --no-daemon --stacktrace --info || true
      
      # 4. 运行 lint 检查
      - name: Run lint
        run: ./gradlew lintDebug --no-daemon --continue || true
      
      # 5. 尝试分模块构建
      - name: Build individual modules
        run: |
          ./gradlew :app:assembleDebug --no-daemon --stacktrace --info || true
          ./gradlew :app:assembleRelease --no-daemon --stacktrace --info || true
      
      # 6. 最后尝试完整构建并捕获详细输出
      - name: Full build with detailed output
        run: |
          ./gradlew build --no-daemon --stacktrace --info --scan 2>&1 | tee build.log
        continue-on-error: true
      
      # 上传所有日志和报告
      - name: Upload all logs and reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: full-debug-logs
          path: |
            **/build/
            build.log
          retention-days: 30
