name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  Build:
    name: Release APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 添加 Android SDK 设置
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Create local.properties
        run: |
          cat << EOF > local.properties
          sdk.dir=/usr/local/lib/android/sdk
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          MAPS_SAFE_CODE=${{ secrets.MAPS_SAFE_CODE }}
          EOF

      # 先尝试清理构建
      - name: Clean project
        run: bash ./gradlew clean --no-daemon

      # 添加 Gradle 属性检查
      - name: Check Gradle properties
        run: |
          if [ -f "gradle.properties" ]; then
            echo "=== gradle.properties ==="
            cat gradle.properties
          fi
          
          if [ -f "local.properties" ]; then
            echo "=== local.properties ==="
            # 隐藏敏感信息
            sed 's/MAPS_API_KEY=.*/MAPS_API_KEY=***/' local.properties | sed 's/MAPS_SAFE_CODE=.*/MAPS_SAFE_CODE=***/'
          fi

      # 分步构建，便于调试
      - name: Build Debug first (for testing)
        run: |
          bash ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Build Release APK
        run: |
          bash ./gradlew assembleRelease --stacktrace --no-daemon --info

      # 如果构建失败，显示详细错误
      - name: Check build results
        if: failure()
        run: |
          echo "=== Build failed, checking reports ==="
          find . -name "problems-report.html" -exec echo "Found: {}" \;
          find . -name "*.log" -exec echo "Log file: {}" \;
          
          # 尝试查看问题报告
          if [ -f "build/reports/problems/problems-report.html" ]; then
            echo "=== Problems Report Content ==="
            cat build/reports/problems/problems-report.html
          fi

      - name: Get Build Tool Version
        run: |
          echo "BUILD_TOOL_VERSION=$(ls -1 /usr/local/lib/android/sdk/build-tools | sort -V | tail -n1)" >> $GITHUB_ENV

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

      - name: Make Changelog
        uses: ardalanamini/auto-changelog@v4.0.4
        id: changelog
        with:
          github-token: ${{ github.token }}
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type: Other Changes
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true

      - name: Release APK
        uses: softprops/action-gh-release@v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
          files: ${{ steps.sign_apk.outputs.signedReleaseFile }}
