name: Android Build Check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Create local.properties
        run: |
          cat << EOF > local.properties
          sdk.dir=$ANDROID_HOME
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          MAPS_SAFE_CODE=${{ secrets.MAPS_SAFE_CODE }}
          EOF
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Clean and build
        run: |
          ./gradlew --stop || true
          ./gradlew clean
          ./gradlew build --no-daemon --stacktrace --no-configuration-cache
      
      - name: Upload build reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-failure-reports
          path: |
            **/build/reports/
            **/build/android-profile/
          retention-days: 30
