name: Build Release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  Build:
    name: Release APK
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 修复：正确创建 local.properties 文件
      - name: Create local.properties
        run: |
          cat << EOF > local.properties
          sdk.dir=/usr/local/lib/android/sdk
          MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}
          MAPS_SAFE_CODE=${{ secrets.MAPS_SAFE_CODE }}
          EOF
          
          # 验证文件内容（隐藏敏感信息）
          echo "=== local.properties 内容验证 ==="
          echo "sdk.dir: $(grep 'sdk.dir' local.properties)"
          echo "MAPS_API_KEY: 已设置"
          echo "MAPS_SAFE_CODE: 已设置"

      # 添加：检查 secrets 插件配置
      - name: Check Secrets Plugin Configuration
        run: |
          if [ -f "app/build.gradle" ]; then
            echo "=== Secrets Plugin 配置检查 ==="
            grep -A 10 -B 10 "secrets-gradle-plugin" app/build.gradle || echo "未找到 secrets plugin 配置"
          fi
          
          # 检查项目级的 secrets 配置
          if [ -f "build.gradle" ]; then
            echo "=== 项目级 build.gradle ==="
            grep -A 5 -B 5 "secrets" build.gradle || echo "未找到项目级 secrets 配置"
          fi

      # 先清理构建
      - name: Clean project
        run: bash ./gradlew clean --no-daemon

      # 构建时添加详细日志
      - name: Build Release APK
        run: |
          bash ./gradlew assembleRelease --stacktrace --no-daemon --info

      - name: Get Build Tool Version
        run: |
          echo "BUILD_TOOL_VERSION=$(ls -1 /usr/local/lib/android/sdk/build-tools | sort -V | tail -n1)" >> $GITHUB_ENV

      # 注意：签名配置需要调整，因为你的 keystore 文件不在 CI 环境中
      - name: Setup Signing
        run: |
          # 创建 keystore 目录
          mkdir -p ../keystore
          # 这里你需要提供实际的 keystore 文件或从 secrets 中恢复

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-signed
          path: ${{ steps.sign_apk.outputs.signedReleaseFile }}

      - name: Make Changelog
        uses: ardalanamini/auto-changelog@v4.0.4
        id: changelog
        with:
          github-token: ${{ github.token }}
          commit-types: |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type: Other Changes
          mention-authors: true
          mention-new-contributors: true
          include-compare-link: true

      - name: Release APK
        uses: softprops/action-gh-release@v2.3.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ github.token }}
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
          files: ${{ steps.sign_apk.outputs.signedReleaseFile }}
